---
- name: Ensure SSH server is installed
  package:
    name: openssh-server
    state: present

- name: Ensure SSH daemon is enabled
  service:
    name: sshd
    enabled: true

- name: SSH daemon configuration - global
  block:
    - name: SSH daemon configuration - base
      template:
        src: "etc/ssh/{{ ansible_facts['os_family'] }}-{{ ansible_distribution_major_version }}-sshd_config.j2"
        dest: "/etc/ssh/sshd_config"
        owner: root
        group: root
        mode: '0600'
        validate: /usr/sbin/sshd -t -f %s
        backup: true
      notify: restart_sshd
  rescue:
    - name: Print errors for configuration and validation
      debug:
        msg: 'Error in SSH daemon configuration or template'

- name: Remove DSA keys
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ssh/ssh_host_dsa_key.pub
    - /etc/ssh/ssh_host_dsa_key