---
- name: Standard system configuration variables
  block:
    - name: Loading variables from OS common
      include_vars: "{{ item }}"
      with_items:
        - "{{ ansible_distribution }}.yml"
    
    - name: Create overrides if we're an IPA replica
      include_vars: "{{ item }}"
      with_first_found:
        - "ipaserver.yml"
      when: "'ipaserver' in group_names"

    - name: Check if system is EFI
      stat:
        path: "/sys/firmware/efi"
      register: efi_installed

  always:
    - debug: msg="Variables are now loaded"