---
ipagroups:
  - group: hbjy
    description: HBJY User Accounts
    user:
      - hayden
  - group: hbjyadm
    description: HBJY Operational Admin Accounts
    user:
      - hayden
  - group: services
    description: HBJY Service Accounts
    user:
      - userman
      - hostman
      - kerbman
  - group: tower_administrators
    description: Ansible Tower administrators
    user:
      - hayden
  - group: tower_users
    description: Ansible Tower users
    user: []
