---
- name: Create initial users
  hosts: ipaserver
  become: true
  gather_facts: false
  vars_files:
    - vars/vaults/encpass.yml
    - vars/ipa/users.yml
    - vars/ipa/svcusers.yml
    - vars/ipa/groups.yml
    - vars/ipa/ipaprivs.yml

  tasks:
    - name: Checking for user variables
      assert:
        that:
          - ipaadmin_password | mandatory
          - users | mandatory
          - ipagroups | mandatory
        success_msg: Required variables provided
        fail_msg: We are missing users or IPA admin password
    
    - name: Configure users
      import_tasks: import-hbjyusers.yml
    
    - name: Configure groups
      import_tasks: import-hbjygroups.yml
    
    - name: Configure sudo
      import_tasks: import-hbjysudo.yml

    - name: Configure service privileges
      import_tasks: import-hbjyipaprivs.yml
